已连接到 test_numpy2 (Python 3.12.3)

In [1]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(-1, 2)
weights = np.random.rand(5, 2)
print(weights)
weights = np.broadcast_to(weights, arr.shape).astype(float)
print(weights)
weights /= weights.sum(axis=1, keepdims=True)
print(weights)

NameError: name 'np' is not defined

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(-1, 2)
weights = np.random.rand(5, 2)
print(weights)
weights = np.broadcast_to(weights, arr.shape).astype(float)
print(weights)
weights /= weights.sum(axis=1, keepdims=True)
print(weights)

[[0.48738152 0.04043403]
 [0.82982153 0.07186787]
 [0.52175722 0.52406506]
 [0.59168608 0.00586587]
 [0.96877603 0.00486927]]
[[0.48738152 0.04043403]
 [0.82982153 0.07186787]
 [0.52175722 0.52406506]
 [0.59168608 0.00586587]
 [0.96877603 0.00486927]]
[[0.92339363 0.07660637]
 [0.92029643 0.07970357]
 [0.49889664 0.50110336]
 [0.99018349 0.00981651]
 [0.99499892 0.00500108]]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(-1, 2)
weights = np.random.rand(2)
print(weights)
weights = np.broadcast_to(weights, arr.shape).astype(float)
print(weights)
weights /= weights.sum(axis=1, keepdims=True)
print(weights)

[0.71613129 0.38649263]
[[0.71613129 0.38649263]
 [0.71613129 0.38649263]
 [0.71613129 0.38649263]
 [0.71613129 0.38649263]
 [0.71613129 0.38649263]]
[[0.64947919 0.35052081]
 [0.64947919 0.35052081]
 [0.64947919 0.35052081]
 [0.64947919 0.35052081]
 [0.64947919 0.35052081]]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(-1, 2)
weights = np.random.rand(2)
print("init", weights)
weights = np.broadcast_to(weights, arr.shape).astype(float)
print("broadcast", weights)
weights /= weights.sum(axis=1, keepdims=True)
print("normalize", weights)

init [0.97370842 0.06602855]
broadcast [[0.97370842 0.06602855]
 [0.97370842 0.06602855]
 [0.97370842 0.06602855]
 [0.97370842 0.06602855]
 [0.97370842 0.06602855]]
normalize [[0.93649495 0.06350505]
 [0.93649495 0.06350505]
 [0.93649495 0.06350505]
 [0.93649495 0.06350505]
 [0.93649495 0.06350505]]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(-1, 2)
weights = np.random.rand(2)
print("init", weights)
weights = np.broadcast_to(weights, arr.shape).astype(float)
print("broadcast", weights)
weights /= weights.sum(axis=0, keepdims=True)
print("normalize", weights)

init [0.96980208 0.20412354]
broadcast [[0.96980208 0.20412354]
 [0.96980208 0.20412354]
 [0.96980208 0.20412354]
 [0.96980208 0.20412354]
 [0.96980208 0.20412354]]
normalize [[0.2 0.2]
 [0.2 0.2]
 [0.2 0.2]
 [0.2 0.2]
 [0.2 0.2]]


In [6]:
import numpy as np

q = np.asarray([0, 0.1, 0.15])
print(q)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(5, 2)
w = np.ones_like(arr)

print(np.quantile(arr, q, axis=[1]))

[0.   0.1  0.15]
[[1.   3.   5.   7.   9.  ]
 [1.1  3.1  5.1  7.1  9.1 ]
 [1.15 3.15 5.15 7.15 9.15]]


In [7]:
import numpy as np

q = np.asarray([0, 0.1, 0.15])
print(q)

arr = np.rrange(100).reshape(10, 5, 2)
w = np.ones_like(arr)

print(np.quantile(arr, q, axis=[1]))

[0.   0.1  0.15]


AttributeError: module 'numpy' has no attribute 'rrange'

In [8]:
import numpy as np

q = np.asarray([0, 0.1, 0.15])
print(q)

arr = np.arange(100).reshape(10, 5, 2)
w = np.ones_like(arr)

print(np.quantile(arr, q, axis=[1]))

[0.   0.1  0.15]
[[[ 0.   1. ]
  [10.  11. ]
  [20.  21. ]
  [30.  31. ]
  [40.  41. ]
  [50.  51. ]
  [60.  61. ]
  [70.  71. ]
  [80.  81. ]
  [90.  91. ]]

 [[ 0.8  1.8]
  [10.8 11.8]
  [20.8 21.8]
  [30.8 31.8]
  [40.8 41.8]
  [50.8 51.8]
  [60.8 61.8]
  [70.8 71.8]
  [80.8 81.8]
  [90.8 91.8]]

 [[ 1.2  2.2]
  [11.2 12.2]
  [21.2 22.2]
  [31.2 32.2]
  [41.2 42.2]
  [51.2 52.2]
  [61.2 62.2]
  [71.2 72.2]
  [81.2 82.2]
  [91.2 92.2]]]


In [9]:
import numpy as np

q = np.asarray([0, 0.1, 0.15])
print(q)

arr = np.arange(24).reshape(2, 3, 4)
w = np.ones_like(arr)

print(np.quantile(arr, q, axis=[1]))

[0.   0.1  0.15]
[[[ 0.   1.   2.   3. ]
  [12.  13.  14.  15. ]]

 [[ 0.8  1.8  2.8  3.8]
  [12.8 13.8 14.8 15.8]]

 [[ 1.2  2.2  3.2  4.2]
  [13.2 14.2 15.2 16.2]]]


In [10]:
import numpy as np

q = np.asarray([0, 0.1, 0.15])
print(q)

arr = np.arange(24).reshape(2, 3, 4)
w = np.ones_like(arr)

print(np.quantile(arr, q, axis=[1, 2]))

[0.   0.1  0.15]
[[ 0.   12.  ]
 [ 1.1  13.1 ]
 [ 1.65 13.65]]


In [11]:
import numpy as np

q = np.asarray([0, 0.1, 0.15])

arr = np.arange(24).reshape(2, 3, 4)
w = np.ones_like(arr)

print(np.quantile(arr, q, axis=[1, 2]))

[[ 0.   12.  ]
 [ 1.1  13.1 ]
 [ 1.65 13.65]]


In [12]:
import numpy as np

q = np.asarray([0, 0.1, 0.15])

arr = np.arange(24).reshape(2, 3, 4)
w = np.ones_like(arr)
print(arr)
print(np.quantile(arr, q, axis=[1, 2]))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0.   12.  ]
 [ 1.1  13.1 ]
 [ 1.65 13.65]]


In [13]:
import numpy as np

q = np.asarray([0, 0.5])

arr = np.arange(24).reshape(2, 3, 4)
w = np.ones_like(arr)
print(arr)
print(np.quantile(arr, q, axis=[1, 2]))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0.  12. ]
 [ 5.5 17.5]]


In [14]:
def quantile(a, q, axis=0, weights=None):
    if axis < 0:
        axis += len(a.shape)
    if weights is None:
        return np.quantile(a, q)
    weights = np.broadcast_to(weights, a.shape).astype(float)
    weights /= weights.sum(axis=axis, keepdims=True)

    ashape = a.shape
    axislen = ashape[axis]

    sorted_args = np.argsort(a, axis=axis)
    sorted_a = np.take_along_axis(a, sorted_args, axis=axis)

    # weights on the first and last

    a_swap = np.swapaxes(sorted_a, axis, -1)
    w_swap = np.swapaxes(weights, axis, -1)
    a_flatten = a_swap.reshape(-1, axislen)
    w_flatten = w_swap.reshape(-1, axislen)

    # probably wanna change this into ufunc
    q_flatten = np.zeros((a_flatten.shape[0], len(q)))
    for al, wl, ql in zip(a_flatten, w_flatten, q_flatten):
        print(al, wl, ql)
        ql[:] = np.interp(q, wl.cumsum(), al)
    return q_flatten

In [15]:
print(quantile(arr, q, weights=w))

[ 0 12] [0.5 0.5] [0. 0.]
[ 4 16] [0.5 0.5] [0. 0.]
[ 8 20] [0.5 0.5] [0. 0.]
[ 1 13] [0.5 0.5] [0. 0.]
[ 5 17] [0.5 0.5] [0. 0.]
[ 9 21] [0.5 0.5] [0. 0.]
[ 2 14] [0.5 0.5] [0. 0.]
[ 6 18] [0.5 0.5] [0. 0.]
[10 22] [0.5 0.5] [0. 0.]
[ 3 15] [0.5 0.5] [0. 0.]
[ 7 19] [0.5 0.5] [0. 0.]
[11 23] [0.5 0.5] [0. 0.]
[[ 0.  0.]
 [ 4.  4.]
 [ 8.  8.]
 [ 1.  1.]
 [ 5.  5.]
 [ 9.  9.]
 [ 2.  2.]
 [ 6.  6.]
 [10. 10.]
 [ 3.  3.]
 [ 7.  7.]
 [11. 11.]]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr.reshape(-1, 2)
weights = np.random.rand(2)
print("init", weights)
weights = np.broadcast_to(weights, arr.shape).astype(float)
print("broadcast", weights)
weights /= weights.sum(axis=0, keepdims=True)
print("normalize", weights)